### ISSUE TITLE
Breaks when using breakpoints in VS

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-unity#12]
When using breakpoints in visual studio and whilst in a topic or similar it makes user to disconnect ( which makes sense ). Not sure if there's a magic way to prevent that so it makes debugging easier.

**Comment by novabyte** [comment]
@ArisTsevrenis I've had a look and you should be able to freeze theads in Visual Studio when you hit the breakpoint. I'm not sure how the Unity engine will react in this case - I'm unable to try this out because I don't have access to a Windows machine. Have a look at - https://msdn.microsoft.com/en-us/library/bb157784.aspx#Anchor_3
