### ISSUE TITLE
Exceeded max retry attempts

### ISSUE THREAD

**Issue by aminbarzegari** [heroiclabs/nakama-unity#128]
hello.
We have this error when authenticating:
Exceeded max retry attempts.

What should we do to solve it?

**Comment by novabyte** [comment]
@aminbarzegari It's impossible to help because the only reason that authentication would fail with retry attempts exceeded is if there's some kind of problem with your infrastructure set up of the game server and database server. I suggest you investigate that or run on the Heroic Cloud where it's possible for us to rule things out. Please ask any follow up on a forum post, thanks.
