### ISSUE TITLE
Doesn't support leaderboard rank counts yet

### ISSUE THREAD

**Issue by Spud6703** [heroiclabs/nakama-unity#164]
ListLeaderboardRecordsAsync and other leaderboard methods don't return the new leaderboard rank counts that were introduced in the Nakama server 3.17

**Comment by novabyte** [comment]
@Spud6703 The best way to keep track of unreleased changes is with these two sections of the CHANGELOGs:

- https://github.com/heroiclabs/nakama-unity/blob/master/Packages/Nakama/CHANGELOG.md#unreleased
- https://github.com/heroiclabs/nakama-dotnet/blob/master/CHANGELOG.md#unreleased

Since this is not an issue I'll close it and recommend you keep an eye on the next official release. It's easy to do with GitHub via the "Watch" option.
