### ISSUE TITLE
SSL connection through Unity client doesn't work

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-unity#31]
Trying to connect to the nakama server via SSL in the Unity Editor doesn't work. Error is when you try to login/register: 
ID login '' failed: NError(Code=Unknown,Message=Error getting response stream (Write: The authentication or decryption has failed.): SendFailure)

**Comment by novabyte** [comment]
@ArisTsevrenis This is not enough information to diagnose the issue. As a minimum this would be necessary:

- Your version of Unity.
- The version of the Unity client you use.
- How you handle SSL termination with your server. This includes the exact configuration files.
- What version of Nakama server do you use?
- Are you able to reach the healthcheck endpoint in Nakama via SSL?
- What happens if you try to reach the server via `WWW` in Unity?

I've helped you debug this issue already and shown you that the Unity client has no issue within the Unity editor or via the WebGL builds you need.

![screen shot 2017-06-06 at 11 18 52](https://cloud.githubusercontent.com/assets/229752/26824815/b4f4b8ce-4aaa-11e7-8554-9d5675975aad.png)
