### ISSUE TITLE
MatchMaker returns empty match ID

### ISSUE THREAD

**Issue by leehans** [heroiclabs/nakama-unity#70]
Hi! 

Is it normal for MatchMaker to return an empty/nil match ID for "matched" matches? 

In the following snippet:

```
socket.OnMatchmakerMatched += (object _, IMatchmakerMatched matched) =>
{
        Debug.Log("Got a match with ID: " + matched.MatchId + ", token: " + matched.Token + ", ticket: " + matched.Ticket);
};
```

only `matched.MatchId` is null/empty. Both token and ticket are in tact. Unless there is another way to send real time messages without using the match ID, I can't relay information to other clients via `socket.SendMatchState`, which requires the match ID.

**Comment by novabyte** [comment]
Hey @leehans. With the matchmaker you should join the match with the matchmaker token rather than attempt to join by ID. This is part of the design of the matchmaker although the data structures are shared between match listings and the matchmaker response which is why it appears unexpected.

When the matchmaker ticket is returned you can use it to join the match but the player will not be part of it until that is done.

**Comment by leehans** [comment]
Thanks for that clarification @novabyte ! I'll use this bit of info to proceed.

**Comment by ReGaSLZR** [comment]
Can I request that this be included as a note somewhere in the documentation of Nakama (so as for future users of the plugin not getting stuck here)? :)

**Comment by novabyte** [comment]
Hey @ReGaSLZR. Do you have a draft for what would be good to add as a note somewhere in the SDK code docs or in the README? I'm unsure where to add the information because it's already covered in the main docs [^1].

```csharp
socket.ReceivedMatchmakerMatched += async matched =>
{
    Debug.LogFormat("Received: {0}", matched);
    await socket.JoinMatchAsync(matched);
};
```

[^1]: https://heroiclabs.com/docs/gameplay-matchmaker/#join-a-match

**Comment by ReGaSLZR** [comment]
> Hey @ReGaSLZR. Do you have a draft for what would be good to add as a note somewhere in the SDK code docs or in the README? I'm unsure where to add the information because it's already covered in the main docs [^1](https://heroiclabs.com/docs/gameplay-matchmaker/#join-a-match).
> 
> ```cs
> socket.ReceivedMatchmakerMatched += async matched =>
> {
>     Debug.LogFormat("Received: {0}", matched);
>     await socket.JoinMatchAsync(matched);
> };
> ```

In the part where [Send Data Messages](https://heroiclabs.com/docs/gameplay-multiplayer-realtime/) has its sample code, I would like to suggest mentioning that the matchID is not from the `IMatchmakerMatched` object since it returns empty string (wait, why does this object even have matchID anyway if its value is blank?)

Or, in that `ReceivedMatchmakerMatched`/`JoinMatchAsync` snipped, include a comment to not use the `matched` object for its matchID.

**Comment by novabyte** [comment]
@ReGaSLZR 

> Wait, why does this object even have matchID anyway if its value is blank?
> What is the point of IMatchmakerMatched.matchID anyway? 🤔

We reuse the message type in our API between `CreateMatch` and `MatchmakerMatched` to represent information needed to join a match to play other opponents.

The `CreateMatch` returns the match ID because it's expected to be shared over some other mechanism to players but the matchmaker returns tokens. These tokens are scoped so that they're short lived and cannot be tampered with for other (malicious) players to use to attempt to join the match that they were not matched on.

**Comment by ReGaSLZR** [comment]
@novabyte 
> The `CreateMatch` returns the match ID because it's expected to be shared over some other mechanism to players but the matchmaker returns tokens. These tokens are scoped so that they're short lived and cannot be tampered with for other (malicious) players to use to attempt to join the match that they were not matched on.

So you guys won't put the note -- for IMatchmakerMatched.matchID being blank -- on the documentation. Got it. 👍 

Thanks for the reply, sir. 🙇‍♀

**Comment by mofirouz** [comment]
@ReGaSLZR @novabyte  previous message was letting you know about why the match ID may be empty. We will update the documentation to mention the above and the reasons so developers have a better working knowledge of Nakama’s APIs. Thanks a lot of bringing this up.
