### ISSUE TITLE
How to receive dispatcher.broadcast_message messages?

### ISSUE THREAD

**Issue by tigerpaws01** [heroiclabs/nakama-unity#71]
I am currently using **Nakama Authoritative Multiplayer**. Inside `match_loop`, I would like the players to receive some messages upon meeting some conditions.

As the [document](https://heroiclabs.com/docs/gameplay-multiplayer-server-multiplayer/#match-runtime-api) says, the function `dispatcher.broadcast_message` works. However, I did not find a way for the clients to receive and process the data. 

How should I do this? (I tried `OnMatchState`, but that seems to be for the relayed multiplayer, not the authoritative one.)

Also, is there any way for the client to be noted the change in **Match States**? (or to query the current Match State?)

Thanks in advance.

**Comment by mofirouz** [comment]
OnMatchState is indeed your friend here, for both client-auth and server-auth multiplayer. 

If you aren’t getting messages through it is likely an issue in your Lua or Go code running on the server. 

Jump on Gitter (https://gitter.im/heroiclabs/nakama) and let us know about your code.

Since this isn’t relevant to Unity Client specifically, I’ll close this ticket.
